version: '3.5'

services:
  adblock-blocklist_updater:
    container_name: adblock-blocklist_updater
    image: rossbannerman/adblock_blocklist_updater:latest
    networks:
      - adblock_net
    volumes:
     - adblock_blocklists:/etc/adblock/blocklists
     - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  adblock-dnsmasq:
    container_name: adblock-dnsmasq
    image: rossbannerman/dnsmasq:latest
    cap_add:
      - NET_ADMIN
    networks:
      - adblock_net
    ports:
      - 53:53
      - 53:53/udp
    volumes:
     - adblock_blocklists:/etc/adblock/blocklists
     - ${PWD}/conf/upstream.conf:/etc/adblock/upstream.conf
     - ${PWD}/conf/dnsmasq.conf:/etc/dnsmasq.conf
    restart: always

volumes:
  adblock_blocklists:
    name: adblock_blocklists

networks:
  adblock_net:
    name: adblock_net
